-- =====================================================================
-- PASO 22 — RECIBOS
--
-- Cuando el cliente paga, se le entrega un comprobante. No es una
-- factura fiscal —eso lo maneja el contador— es el recibo de cortesía
-- que confirma «esto lo cobramos, por esto, tal día».
--
-- Dos decisiones que no son obvias:
--
-- 1. NUMERACIÓN PROPIA, no la de la factura. Un recibo es un documento
--    distinto: una factura se puede pagar en dos veces y son dos
--    recibos, y hay cobros que no tienen factura detrás.
--
-- 2. ES UNA FOTO, no una vista. Los importes se copian al emitirlo en
--    vez de leerse del cobro cada vez. Si mañana alguien corrige el
--    monto del cobro, el papel que ya tiene el cliente no puede cambiar
--    solo: el recibo dice lo que decía el día que se entregó. Por eso
--    también el borrado del cobro es `restrict` — un recibo entregado no
--    se puede quedar sin respaldo.
--
-- Requiere 03_schema (payments) y conviene tener 16/17 (facturas), pero
-- funciona sin ellas: un recibo puede no tener factura detrás.
-- Es idempotente.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. El esquema, explícito
--
-- El SQL Editor no siempre corre con "public" en el search_path, y un
-- "create table" que nombra un enum sin calificar falla con
-- «type "currency" does not exist» aunque el tipo esté ahí, creado por
-- 03_schema.sql. Se fija el camino Y además los tipos van con esquema:
-- cualquiera de las dos cosas alcanza sola, las dos juntas hacen que el
-- script no dependa de cómo se lo ejecute.
-- ---------------------------------------------------------------------
set search_path = public;


-- ---------------------------------------------------------------------
-- 1. La tabla
--
-- `numero` es un correlativo propio, por identidad. Puede saltarse un
-- número si una inserción falla, y está bien: no es un comprobante
-- fiscal, nadie audita la secuencia, y la alternativa —tomar el máximo y
-- sumarle uno— da números repetidos apenas dos personas emiten a la vez.
-- ---------------------------------------------------------------------
create table if not exists recibos (
  id          uuid primary key default gen_random_uuid(),
  numero      integer generated by default as identity unique,

  -- Un recibo respalda UN cobro. Restrict: el cobro no se puede borrar
  -- mientras exista el papel que el cliente tiene en la mano.
  payment_id  uuid not null unique references payments(id) on delete restrict,

  emitido_on  date not null default current_date,

  -- ---- La foto del momento de emisión --------------------------------
  cliente_nombre  text not null,
  concepto        text not null,

  -- Lo que se cobró, en la moneda en que efectivamente entró.
  importe         numeric(14,2) not null check (importe > 0),
  moneda          public.currency not null,

  -- Sólo cuando se cobró en una moneda distinta a la facturada: cuánto
  -- saldaba de la deuda original y a qué cotización. Es el dato que le
  -- da tranquilidad al cliente («me tomaron el dólar a 1530») y el que
  -- evita la discusión tres meses después.
  importe_saldado numeric(14,2),
  moneda_saldada  public.currency,
  cotizacion      numeric(12,4),

  -- El número de la factura que salda, como texto: si la factura se
  -- borra, el recibo tiene que seguir diciendo a qué correspondía.
  factura_numero  text not null default '',

  notas       text not null default '',
  created_at  timestamptz not null default now(),

  -- Los tres datos de la conversión van juntos o no van: una cotización
  -- sin el importe que convirtió no se puede verificar.
  constraint recibos_conversion_completa check (
    (importe_saldado is null and moneda_saldada is null and cotizacion is null)
    or
    (importe_saldado is not null and moneda_saldada is not null and cotizacion > 0)
  )
);

create index if not exists recibos_emitido_idx on recibos (emitido_on desc);
create index if not exists recibos_numero_idx  on recibos (numero desc);

alter table recibos enable row level security;
drop policy if exists authenticated_all on recibos;
create policy authenticated_all on recibos
  for all to authenticated using (true) with check (true);


-- ---------------------------------------------------------------------
-- 2. Emitir
--
-- Toma la foto sola, leyendo del cobro y de su factura. Que lo arme la
-- base y no el cliente evita que dos pantallas distintas copien los
-- datos de forma distinta, y que alguien emita un recibo por un importe
-- que no es el del cobro.
--
-- Si el cobro ya tiene recibo devuelve el que hay, en vez de fallar:
-- tocar dos veces el botón es lo más esperable del mundo y no tiene por
-- qué ser un error.
-- ---------------------------------------------------------------------
create or replace function emitir_recibo(p_payment_id uuid, p_notas text default '')
returns recibos
language plpgsql
security definer
set search_path = public
as $$
declare
  ya       recibos;
  pago     record;
  cli      text;
  fac_num  text := '';
  fac_mon  public.currency;
  fac_imp  numeric;
  nuevo    recibos;
begin
  select * into ya from recibos where payment_id = p_payment_id;
  if found then
    return ya;
  end if;

  select p.*, pr.name as proyecto_nombre
    into pago
    from payments p
    left join projects pr on pr.id = p.project_id
   where p.id = p_payment_id;

  if not found then
    raise exception 'No existe el cobro %', p_payment_id;
  end if;

  -- El cliente: el de la factura si la hay, si no el del proyecto.
  if to_regclass('public.facturas') is not null and pago.factura_id is not null then
    execute 'select f.numero, f.moneda, f.importe, c.name
               from facturas f left join clients c on c.id = f.cliente_id
              where f.id = $1'
      into fac_num, fac_mon, fac_imp, cli
      using pago.factura_id;
  end if;

  if cli is null then
    select c.name into cli
      from projects pr join clients c on c.id = pr.client_id
     where pr.id = pago.project_id;
  end if;

  insert into recibos (
    payment_id, cliente_nombre, concepto, importe, moneda,
    importe_saldado, moneda_saldada, cotizacion, factura_numero, notas
  )
  values (
    p_payment_id,
    coalesce(nullif(btrim(cli), ''), 'Consumidor final'),
    coalesce(nullif(btrim(pago.concept), ''),
             coalesce(pago.proyecto_nombre, 'Servicios')),
    pago.amount,
    pago.currency,
    -- La conversión sólo se guarda si de verdad hubo uno: cobrado en una
    -- moneda, saldando una deuda en otra.
    case when pago.applied_amount is not null and fac_mon is not null
              and fac_mon <> pago.currency
         then pago.applied_amount end,
    case when pago.applied_amount is not null and fac_mon is not null
              and fac_mon <> pago.currency
         then fac_mon end,
    case when pago.applied_amount is not null and fac_mon is not null
              and fac_mon <> pago.currency and pago.applied_amount > 0
         then round(pago.amount / pago.applied_amount, 4) end,
    coalesce(fac_num, ''),
    coalesce(p_notas, '')
  )
  returning * into nuevo;

  -- Que el equipo se entere de que salió un comprobante.
  if to_regprocedure('public.notificar(text,text,text,text)') is not null then
    perform notificar(
      'Recibo N° ' || nuevo.numero || ' · ' || nuevo.cliente_nombre,
      nuevo.moneda::text || ' ' || to_char(nuevo.importe, 'FM999G999G999D00')
        || ' · ' || nuevo.concepto,
      '/cobros'
    );
  end if;

  return nuevo;
end $$;

revoke all on function emitir_recibo(uuid, text) from public;
grant execute on function emitir_recibo(uuid, text) to authenticated;


-- ---------------------------------------------------------------------
-- 3. Verificación
-- ---------------------------------------------------------------------
select
  (select count(*) from recibos)                                   as recibos_emitidos,
  (select coalesce(max(numero), 0) from recibos)                   as ultimo_numero,
  (to_regprocedure('public.emitir_recibo(uuid,text)') is not null) as funcion_lista;
