-- =====================================================================
-- PASO 23 — PROPUESTAS
--
-- El presupuesto que se le manda al cliente antes de que haya trabajo,
-- plata ni proyecto. Lo arma el vendedor: escribe en criollo lo que se
-- acordó, la IA lo estructura, él lo corrige y lo baja en PDF.
--
-- Tres decisiones que no son obvias:
--
-- 1. SE GUARDA AL DESCARGAR, no al generar. Un borrador que nunca llegó
--    a PDF no es una propuesta: es alguien probando. Si se guardara todo,
--    el historial se llenaría de ensayos y dejaría de servir para la
--    única pregunta que importa: «¿qué le mandamos a este cliente?».
--
-- 2. EL CONTENIDO VA EN UN JSONB, no en tablas de ítems. Una propuesta no
--    se vuelve a calcular ni suma a ningún total: es un papel que se
--    mandó. Normalizarla sería armar un modelo para consultas que nadie
--    va a hacer, y obligaría a migrar el esquema cada vez que cambie la
--    plantilla. Las columnas sueltas de arriba existen sólo para poder
--    listar y buscar sin abrir el json.
--
-- 3. NO TOCA NINGUNA OTRA TABLA. No hay FK a clients ni a projects, a
--    propósito: se cotiza todo el tiempo a gente que todavía no es
--    cliente, y una propuesta que no se puede emitir porque falta cargar
--    el cliente es una propuesta que se termina haciendo en Word.
--
-- Requiere 03_schema (el tipo `currency`). El aviso por push es opcional:
-- si 20_push no corrió, la función lo saltea.
-- Es idempotente.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. El esquema, explícito
--
-- El SQL Editor no siempre corre con "public" en el search_path, y un
-- "create table" que nombra un enum sin calificar falla con
-- «type "currency" does not exist» aunque el tipo esté creado. Nos pasó
-- con el 22. Se fija el camino Y además el tipo va calificado.
-- ---------------------------------------------------------------------
set search_path = public;


-- ---------------------------------------------------------------------
-- 1. La tabla
--
-- `numero` es correlativo propio, por identidad, igual que los recibos.
-- Puede saltarse un número si una inserción falla y está bien: no es un
-- comprobante fiscal, y la alternativa —tomar el máximo y sumarle uno—
-- da números repetidos apenas dos personas emiten a la vez.
-- ---------------------------------------------------------------------
create table if not exists propuestas (
  id              uuid primary key default gen_random_uuid(),
  numero          integer generated by default as identity unique,
  emitida_on      date not null default current_date,
  plantilla       text not null check (plantilla in ('corta', 'larga')),

  -- ---- Para listar sin abrir el json ---------------------------------
  cliente_nombre  text not null,
  titulo          text not null,
  total           numeric(14,2) not null default 0 check (total >= 0),
  moneda          public.currency not null,
  validez_dias    integer,

  -- ---- La foto completa ----------------------------------------------
  -- Con esto se vuelve a dibujar el PDF idéntico, sin volver a pasar por
  -- la IA. Es lo que hace que «mandámelo de nuevo» sea gratis.
  contenido       jsonb not null,

  created_at      timestamptz not null default now()
);

create index if not exists propuestas_emitida_idx on propuestas (emitida_on desc);
create index if not exists propuestas_numero_idx  on propuestas (numero desc);
create index if not exists propuestas_cliente_idx on propuestas (lower(cliente_nombre));

alter table propuestas enable row level security;
drop policy if exists authenticated_all on propuestas;
create policy authenticated_all on propuestas
  for all to authenticated using (true) with check (true);


-- ---------------------------------------------------------------------
-- 2. Emitir
--
-- Las columnas de listado salen del propio json y no de argumentos
-- sueltos: así no puede pasar que el PDF diga una cosa y la lista otra.
--
-- A diferencia de `emitir_recibo`, NO es idempotente. Un recibo respalda
-- un cobro y hay uno solo por cobro; una propuesta se puede rehacer con
-- otros números las veces que haga falta, y cada una es un papel
-- distinto que salió para afuera.
-- ---------------------------------------------------------------------
create or replace function emitir_propuesta(p_contenido jsonb, p_plantilla text)
returns propuestas
language plpgsql
security definer
set search_path = public
as $$
declare
  nuevo   propuestas;
  v_total numeric(14,2);
  v_mon   public.currency;
  v_cli   text;
  v_tit   text;
begin
  if p_plantilla not in ('corta', 'larga') then
    raise exception 'Plantilla desconocida: %', p_plantilla;
  end if;

  -- El total se recalcula acá y no se acepta del cliente: es el número
  -- que después se mira para saber cuánto hay cotizado en la calle, y no
  -- puede depender de que la pantalla haya sumado bien. Los ítems sin
  -- precio no suman —el PDF también los deja fuera y lo aclara al pie.
  select coalesce(sum((i->>'cantidad')::numeric * (i->>'precioUnitario')::numeric), 0)
    into v_total
    from jsonb_array_elements(coalesce(p_contenido->'items', '[]'::jsonb)) as i
   where i->>'precioUnitario' is not null
     and i->>'precioUnitario' <> '';

  v_mon := coalesce(nullif(p_contenido->>'moneda', ''), 'USD')::public.currency;
  v_cli := coalesce(nullif(btrim(p_contenido#>>'{cliente,nombre}'), ''), 'Sin especificar');
  v_tit := coalesce(nullif(btrim(p_contenido->>'titulo'), ''), 'Propuesta');

  insert into propuestas (
    plantilla, cliente_nombre, titulo, total, moneda, validez_dias, contenido
  )
  values (
    p_plantilla, v_cli, v_tit, v_total, v_mon,
    nullif(p_contenido->>'validezDias', '')::integer,
    p_contenido
  )
  returning * into nuevo;

  -- Que los socios se enteren de que salió una cotización y por cuánto,
  -- sin tener que preguntar. Es la otra mitad del pedido.
  if to_regprocedure('public.notificar(text,text,text,text)') is not null then
    perform notificar(
      'Propuesta N° ' || nuevo.numero || ' · ' || nuevo.cliente_nombre,
      -- El monto SIEMPRE con el código de moneda: USD y ARS comparten el
      -- «$» y un «$625» en un aviso se lee como pesos.
      nuevo.moneda::text || ' ' || to_char(nuevo.total, 'FM999G999G999D00')
        || ' · ' || nuevo.titulo,
      '/propuestas'
    );
  end if;

  return nuevo;
end $$;

revoke all on function emitir_propuesta(jsonb, text) from public;
grant execute on function emitir_propuesta(jsonb, text) to authenticated;


-- ---------------------------------------------------------------------
-- 3. Verificación
-- ---------------------------------------------------------------------
select
  (select count(*) from propuestas)                                     as propuestas_emitidas,
  (select coalesce(max(numero), 0) from propuestas)                     as ultimo_numero,
  (to_regprocedure('public.emitir_propuesta(jsonb,text)') is not null)  as funcion_lista;
